# SHA1:f35ff6959e870f5446d1c869ff7bb559d01761af
#
# This file is autogenerated by pip-compile-multi
# To update, run:
#
#    pip-compile-multi
#
-r test.txt
iso8601==2.1.0 \
    --hash=sha256:6b1d3829ee8921c4301998c909f7829fa9ed3cbdac0d3b16af2d743aed1ba8df \
    --hash=sha256:aac4145c4dcb66ad8b648a02830f5e2ff6c24af20f4f482689be402db2429242
    # via python-subunit
python-subunit==1.4.3 \
    --hash=sha256:67bed9d7a923c3010446e821dac170da1b11bd4133e18095fa86c30d09b15006 \
    --hash=sha256:9ee76092d5b0a02055219763f1aa9e28835f2dd722f03ea9fd8d68e4066b3378
    # via subunitreporter
subunitreporter==23.8.0 \
    --hash=sha256:af710200f4d6ead8be0420083cfb588e593d72a9734e4d65e1303940a3c7c766 \
    --hash=sha256:d0cdcd8d6d5682864a5165120e91d269a5faf551beba97007371841b2e69b5b3
    # via -r requirements/tox.in
wheel==0.41.2 \
    --hash=sha256:0c5ac5ff2afb79ac23ab82bab027a0be7b5dbcf2e54dc50efe4bf507de1f7985 \
    --hash=sha256:75909db2664838d015e3d9139004ee16711748a52c8f336b52882266540215d8
    # via -r requirements/tox.in

# The following packages are considered to be unsafe in a requirements file:
pip==23.2.1 \
    --hash=sha256:7ccf472345f20d35bdc9d1841ff5f313260c2c33fe417f48c30ac46cccabf5be \
    --hash=sha256:fb0bd5435b3200c602b5bf61d2d43c2f13c02e29c1707567ae7fbc514eb9faf2
    # via -r requirements/tox.in
